fix(k8s): unset KAFKA_PORT to avoid conflict

diff --git a/k8s/base/infrastructure/kafka/statefulset.yaml b/k8s/base/infrastructure/kafka/statefulset.yaml
--- a/k8s/base/infrastructure/kafka/statefulset.yaml
+++ b/k8s/base/infrastructure/kafka/statefulset.yaml
@@ -29,11 +29,10 @@ spec:
         - name: wait-for-zookeeper
           image: busybox:1.36
           command:
-            - sh
-            - -c
             - |
-              echo "Waiting for Zookeeper to be ready..."
-              until nc -z zookeeper.eventflow.svc.cluster.local 2181; do
+              unset KAFKA_PORT
+              echo "Starting configure..."
+              /etc/confluent/docker/configure || { echo "Configure failed"; exit 1; }            until nc -z zookeeper.eventflow.svc.cluster.local 2181; do
                 echo "Zookeeper is not ready yet. Waiting..."
                 sleep 2
               done
